#!/usr/bin/env python3
"""
Interactive setup script for RunPod integration with Atomera.
This will guide you through the configuration process.
"""

import os
import sys
from pathlib import Path

def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")

def print_step(number, text):
    """Print a step number."""
    print(f"\n[Step {number}] {text}")
    print("-" * 60)

def get_input(prompt, default=None):
    """Get user input with optional default."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        user_input = input(f"{prompt}: ").strip()
        while not user_input:
            print("This field is required.")
            user_input = input(f"{prompt}: ").strip()
        return user_input

def main():
    print_header("Atomera RunPod Setup")
    print("This script will help you configure Atomera to use RunPod for GPU inference.")
    print("\nBefore you begin, make sure you have:")
    print("  ✓ A RunPod account with API key")
    print("  ✓ Created a RunPod serverless endpoint")
    print("  ✓ Your endpoint ID from the RunPod dashboard")

    input("\nPress Enter to continue...")

    # Step 1: Get RunPod API Key
    print_step(1, "RunPod API Key")
    print("Get your API key from: https://www.runpod.io/console/user/settings")
    api_key = get_input("Enter your RunPod API Key")

    # Step 2: Get Endpoint ID
    print_step(2, "RunPod Endpoint ID")
    print("Find your endpoint ID in the RunPod serverless dashboard.")
    print("It looks like: abc123def456ghi789")
    endpoint_id = get_input("Enter your RunPod Endpoint ID")

    # Step 3: Configuration options
    print_step(3, "Configuration Options")
    poll_interval = get_input("Polling interval (seconds)", "5")
    timeout = get_input("Job timeout (seconds)", "1800")

    # Step 4: Create .env file
    print_step(4, "Creating Configuration File")

    backend_dir = Path(__file__).parent / "backend"
    backend_dir.mkdir(exist_ok=True)

    env_file = backend_dir / ".env"

    env_content = f"""# Atomera RunPod Configuration
# Generated by setup_runpod.py

# RunPod Settings
USE_RUNPOD=true
RUNPOD_API_KEY={api_key}
RUNPOD_ENDPOINT_ID={endpoint_id}
RUNPOD_POLL_INTERVAL={poll_interval}
RUNPOD_TIMEOUT={timeout}

# Backend Settings
DEBUG=false
HOST=0.0.0.0
PORT=8000
"""

    # Check if file already exists
    if env_file.exists():
        overwrite = input(f"\n⚠️  {env_file} already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != 'y':
            print("\n❌ Setup cancelled. Existing .env file was not modified.")
            sys.exit(0)

    # Write the file
    env_file.write_text(env_content)
    print(f"\n✅ Configuration file created: {env_file}")

    # Step 5: Test connection
    print_step(5, "Testing Connection")
    print("Testing your RunPod connection...")

    test_script = backend_dir / "test_runpod_connection.py"
    if test_script.exists():
        import subprocess
        try:
            result = subprocess.run(
                [sys.executable, str(test_script)],
                cwd=str(backend_dir),
                capture_output=True,
                text=True,
                timeout=30
            )
            print(result.stdout)
            if result.returncode == 0:
                print("\n✅ Connection test passed!")
            else:
                print("\n⚠️  Connection test failed. Please check your credentials.")
                print(result.stderr)
        except subprocess.TimeoutExpired:
            print("\n⚠️  Connection test timed out. Please check your internet connection.")
        except Exception as e:
            print(f"\n⚠️  Could not run connection test: {e}")
    else:
        print(f"\n⚠️  Test script not found at {test_script}")
        print("You can manually test the connection later by running:")
        print(f"    cd {backend_dir}")
        print("    python test_runpod_connection.py")

    # Summary
    print_header("Setup Complete!")
    print("Your Atomera instance is now configured to use RunPod.")
    print("\nNext steps:")
    print("  1. Build and push your Docker image (see DEPLOY_TO_RUNPOD.md)")
    print("  2. Create a RunPod endpoint with your Docker image")
    print("  3. Start the Atomera backend:")
    print(f"     cd {backend_dir}")
    print("     python main.py")
    print("  4. Start the frontend in another terminal:")
    print("     cd frontend")
    print("     npm run dev")
    print("\nFor detailed instructions, see: DEPLOY_TO_RUNPOD.md")
    print("\n✨ Happy predicting! ✨\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error during setup: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
